version: '3'
services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - '3306:3306'
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
     build: 
       context: .
       dockerfile: Dockerfile.app
     ports:
       - '3030:3030'
    
     depends_on:
       db:
         condition: service_healthy
  